'use client';
import Link from 'next/link';
import { useRouter } from 'next/router';
import Head from 'next/head';
import React from 'react';

export const metadata = {
  title: 'PostCard',
  description: 'Generated by create next app',
};

const PostCard = ({ id, title, body, slug }) => {
  return (
    <>
      <Link href={`/blog/${id}`} target='_blank'>
        <div className='w-7/12 mx-auto my-4 shadow-lg rounded-sm px-2 py-3 shadow-gray-200'>
          <h3 className='text-2xl text-gray-700 font-bold my-2'>{title}</h3>
          <span className='text-sm bg-gray-400 rounded-md px-2 py-1 italic text-white font-bold'>
            {slug}
          </span>
          <p className='text-base text-gray-500 font-medium my-3'>
            {body.slice(0, 250)}
          </p>
        </div>
      </Link>
    </>
  );
};

export default PostCard;
