import React from 'react';
import { data } from '@/data/data';

export const metadata = {
  title: `Post`,
  description: 'Generated by create next app',
};

const page = ({ params }) => {
  return (
    <>
      <div className='my-14'>
        {
          // Query all the posts where params.id == item.id
          data.filter(item => item.id == params.id).map(post => (
            <div className='w-7/12 mx-auto h-auto'>
              <h3 className='text-2xl text-gray-700 font-semibold my-4'>{post.title}</h3>
              <span className='text-base text-gray-400 font-semibold my-4'>{post.slug}</span>
              <p className='text-xl leading-7 text-gray-900 font-semibold my-4'>{post.body}</p>
            </div>
          ))
        }
      </div >
    </>
  );
};

export default page;
